spring:
  application:
    name: inventory
    version: 1.0.0
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: 'dev'
server:
  port: 8080
springdoc:
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  info:
    env:
      enabled: true
    java:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: '@project.version@'
    app-version: ${spring.application.version}