databaseChangeLog:
  - changeSet:
      id: 1
      author: Ranga
      changes:
        - createTable:
            tableName: inventory
            columns:
              - column:
                  name: id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
                  startWith: 10
              - column:
                  name: book_id
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: on_hand_quantity
                  type: int
                  defaultValue: 0
                  constraints:
                    nullable: false
              - column:
                  name: allocated_quantity
                  type: int
                  defaultValue: 0
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: varchar(20)
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: varchar(20)
              - column:
                  name: updated_at
                  type: timestamp
        - createTable:
            tableName: issued_books
            columns:
              - column:
                  name: id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
                  autoIncrement: true
                  startWith: 10
              - column:
                  name: book_id
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: issued_to
                  type: varchar(20)
                  constraints:
                    nullable: false
              - column:
                  name: issued_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: due_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: returned_at
                  type: timestamp
              - column:
                  name: created_by
                  type: varchar(20)
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: varchar(20)
              - column:
                  name: updated_at
                  type: timestamp
        - insert:
            tableName: inventory
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: book_id
                  value: 1
              - column:
                  name: on_hand_quantity
                  value: 10
              - column:
                  name: allocated_quantity
                  value: 0
              - column:
                  name: created_by
                  value: "Ranga"
              - column:
                  name: created_at
                  value: "2021-01-01 00:00:00"
        - insert:
            tableName: issued_books
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: book_id
                  value: 1
              - column:
                  name: issued_to
                  value: "Ranga"
              - column:
                  name: issued_at
                  value: "2021-01-01 00:00:00"
              - column:
                  name: due_at
                  value: "2021-01-15 00:00:00"
              - column:
                  name: created_by
                  value: "Ranga"
              - column:
                  name: created_at
                  value: "2021-01-01 00:00:00"

