spring:
  application:
    name: books
    version: 1.0.0
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: 'dev'
server:
  port: 8080
springdoc:
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: '@project.version@'
    app-version: ${spring.application.version}
logging:
  level:
    com:
      ranga:
        minilibrary:
          books: INFO
