services:
  config-server:
    image: config-server
    build:
      context: ../config-server
      dockerfile: ../config-server/Dockerfile
    container_name: config_server
    ports:
      - "8888:8888"
    volumes:
      - ../app-configs:/app-configs
    healthcheck:
      test: 'wget -q -O - http://localhost:8888/actuator/health/readiness | grep UP || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700M
  books:
    image: books
    build:
      context: ../books
      dockerfile: ../books/Dockerfile
    container_name: books_ms
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    healthcheck:
      test: 'wget -q -O - http://localhost:8080/actuator/health/readiness | grep UP || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700M
  inventory:
    image: inventory
    build:
      context: ../inventory
      dockerfile: ../inventory/Dockerfile
    container_name: inventory_ms
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    healthcheck:
      test: 'wget -q -O - http://localhost:8080/actuator/health/readiness | grep UP || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700M