services:
  config-server:
    image: config-server
    build:
      context: ../config-server
      dockerfile: ../config-server/Dockerfile
    container_name: config_server
    ports:
      - "8888:8888"
    volumes:
      - ../app-configs:/app-configs
    healthcheck:
      test: 'wget -q -O - http://localhost:8888/actuator/health/readiness | grep UP || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  books:
    image: books
    build:
      context: ../books
      dockerfile: ../books/Dockerfile
    container_name: books_ms
    ports:
      - "8080:8080"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  inventory:
    image: inventory
    build:
      context: ../inventory
      dockerfile: ../inventory/Dockerfile
    container_name: inventory_ms
    ports:
      - "8090:8080"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  mini-book-library-network:
    driver: bridge