spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booksdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: create
      show-sql: true
  liquibase:
    change-log: db/changelog/changelog.yml

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: '@project.version@'
    app-version: ${spring.application.version}

books:
  contact:
    message: "Hello from books-service"
    contact-details:
      email: "{cipher}08e75baa5adb50d1f3e4a9e37a05be083eecc659bfb55dcdd9a730cc12ecbba3f513c9cc78ab13073dd86bd8c33ec342"
      name: "Default Admin Ranga"
    on-call-support:
      - "123-456-7890"
      - "098-765-4321"
      - "135-792-4680"
